baseURL = 'http://www.sceco.org.uk/'
languageCode = 'en-gb'
title = 'Streatham Commmon Enviromental CoOperative'
theme = 'whisper'
# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30


[params]
homepage_button_link = '/docs'
homepage_button_text = 'Read More Docs'
#  homepage_intro = 'Campaigning for Streatham Common.'
#  homepage_image = '/sceco.gif'


[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 3


[params.logo]
      mobile = "/sceco.gif"
      standard  = "/sceco.gif"


[module]
 [[module.imports]]
   path = 'github.com/mrhelloboy/seven'
 [module.hugoVersion]
   extended = false
   min      = "0.112.0"
 [[module.mounts]]
   source = "assets"
   target = "assets"
 [[module.mounts]]
   source = "hugo_stats.json"
   target = "assets/watching/hugo_stats.json"

[build]
 writeStats = true
 [[build.cachebusters]]
   source = "assets/watching/hugo_stats\\.json"
   target = "styles\\.css"
 [[build.cachebusters]]
   source = "(postcss|tailwind)\\.config\\.js"
   target = "css"
 [[build.cachebusters]]
   source = "assets/.*\\.(js|ts|jsx|tsx)"
   target = "js"
 [[build.cachebusters]]
   source = "assets/.*\\.(.*)$"
   target = "$1"