baseURL = 'http://www.sceco.org.uk/'
languageCode = 'en-gb'
title = 'Streatham Commmon Enviromental CoOperative '
theme = 'whisper'

[params.logo]
      mobile = "/sceco.gif"
      standard  = "/sceco.gif"