version: '3'

tasks:
  dia:
    deps: [dupes]
    cmds:
      - echo "Doing it all"
      
  dupes:
    cmds:
      - cp -rf ./content/docs/Campaign2024/campaign.md ./content/docs/Campaign2024/as_pdf.md
      - sed -i 's/title\:\ 2024\ SCECO/title\:\ AsPDF\ SCECO/' ./content/docs/Campaign2024/as_pdf.md
      - sed -i '2a layout\:\ pdflayout' ./content/docs/Campaign2024/as_pdf.md
      #./content/docs/Campaign2023/_index.md

  publish:
    cmds:
      - git commit -am "Updating from taskfile"
      - git push